/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package irisbaby;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author bruno
 */
public class IrisBaby extends javax.swing.JFrame implements KeyListener {

    String path = null;
    File mp3File = null;
    MP3 musica = null;
    boolean primeiraVezTocando = true;
    Dimension dimension = new Dimension(2000, 2000);

    /**
     * Creates new form IrisBaby
     */
    public IrisBaby() {
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/capa.jpg"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setMinimumSize(new java.awt.Dimension(1440, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IrisBaby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IrisBaby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IrisBaby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IrisBaby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                IrisBaby irisBaby = new IrisBaby();
                irisBaby.setVisible(true);
                irisBaby.addKeyListener(irisBaby);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public void keyPressed(KeyEvent e) {
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/capa.jpg")));
        if (e.getKeyCode() == KeyEvent.VK_A) {
            new Thread() {

                public void run() {
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/orgao.jpg")));
                    if (primeiraVezTocando) {
                        primeiraVezTocando = false;
                        path = "sons/orgao.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    } else {
                        musica.stop();
                        path = "sons/orgao.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    }
                }
            }.start();
        } else if (e.getKeyCode() == KeyEvent.VK_B) {
            new Thread() {

                public void run() {
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/orgao.jpg")));
                    if (primeiraVezTocando) {
                        primeiraVezTocando = false;
                        path = "sons/orgao2.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    } else {
                        musica.stop();
                        path = "sons/orgao2.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    }
                }
            }.start();
        } else if (e.getKeyCode() == KeyEvent.VK_C) {
            new Thread() {

                public void run() {
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gato.jpeg")));
                    if (primeiraVezTocando) {
                        primeiraVezTocando = false;
                        path = "sons/gato.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    } else {
                        musica.stop();
                        path = "sons/gato.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    }
                }
            }.start();
        } else if (e.getKeyCode() == KeyEvent.VK_D) {
            new Thread() {

                public void run() {
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gato.jpeg")));
                    if (primeiraVezTocando) {
                        primeiraVezTocando = false;
                        path = "sons/gato2.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    } else {
                        musica.stop();
                        path = "sons/gato2.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    }
                }
            }.start();
        } else if (e.getKeyCode() == KeyEvent.VK_E) {
            new Thread() {

                public void run() {
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/passaro.jpg")));
                    if (primeiraVezTocando) {
                        primeiraVezTocando = false;
                        path = "sons/passaro.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    } else {
                        musica.stop();
                        path = "sons/passaro.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    }
                }
            }.start();
        } else if (e.getKeyCode() == KeyEvent.VK_F) {
            new Thread() {

                public void run() {
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cavalo.jpg")));
                    if (primeiraVezTocando) {
                        primeiraVezTocando = false;
                        path = "sons/cavalo.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    } else {
                        musica.stop();
                        path = "sons/cavalo.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    }
                }
            }.start();
        } else if (e.getKeyCode() == KeyEvent.VK_G) {
            new Thread() {

                public void run() {
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/elefante.jpg")));
                    if (primeiraVezTocando) {
                        primeiraVezTocando = false;
                        path = "sons/elefante.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    } else {
                        musica.stop();
                        path = "sons/elefante.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    }
                }
            }.start();
        } else if (e.getKeyCode() == KeyEvent.VK_H) {
            new Thread() {

                public void run() {
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/porco.jpg")));
                    if (primeiraVezTocando) {
                        primeiraVezTocando = false;
                        path = "sons/porco.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    } else {
                        musica.stop();
                        path = "sons/porco.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    }
                }
            }.start();
        } else if (e.getKeyCode() == KeyEvent.VK_I) {
            new Thread() {

                public void run() {
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cachorro.jpg")));
                    if (primeiraVezTocando) {
                        primeiraVezTocando = false;
                        path = "sons/cachorro.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    } else {
                        musica.stop();
                        path = "sons/cachorro.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    }
                }
            }.start();
        } else if (e.getKeyCode() == KeyEvent.VK_J) {
            new Thread() {

                public void run() {
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/galinha.jpg")));
                    if (primeiraVezTocando) {
                        primeiraVezTocando = false;
                        path = "sons/galinha.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    } else {
                        musica.stop();
                        path = "sons/galinha.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    }
                }
            }.start();
        } else if (e.getKeyCode() == KeyEvent.VK_K) {
            new Thread() {

                public void run() {
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lobo.jpg")));
                    if (primeiraVezTocando) {
                        primeiraVezTocando = false;
                        path = "sons/lobo.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    } else {
                        musica.stop();
                        path = "sons/lobo.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    }
                }
            }.start();
        } else if (e.getKeyCode() == KeyEvent.VK_L) {
            new Thread() {

                public void run() {
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/macaco.png")));
                    if (primeiraVezTocando) {
                        primeiraVezTocando = false;
                        path = "sons/macaco.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    } else {
                        musica.stop();
                        path = "sons/macaco.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    }
                }
            }.start();
        } else if (e.getKeyCode() == KeyEvent.VK_M) {
            new Thread() {

                public void run() {
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/trompete.jpg")));
                    if (primeiraVezTocando) {
                        primeiraVezTocando = false;
                        path = "sons/trompete.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    } else {
                        musica.stop();
                        path = "sons/trompete.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    }
                }
            }.start();
        } else if (e.getKeyCode() == KeyEvent.VK_N) {
            new Thread() {

                public void run() {
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/grito.jpg")));
                    if (primeiraVezTocando) {
                        primeiraVezTocando = false;
                        path = "sons/grito.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    } else {
                        musica.stop();
                        path = "sons/grito.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    }
                }
            }.start();
        } else if (e.getKeyCode() == KeyEvent.VK_O) {
            new Thread() {

                public void run() {
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lobo.jpg")));
                    if (primeiraVezTocando) {
                        primeiraVezTocando = false;
                        path = "sons/lobo2.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    } else {
                        musica.stop();
                        path = "sons/lobo2.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    }
                }
            }.start();
        } else if (e.getKeyCode() == KeyEvent.VK_P) {
            new Thread() {

                public void run() {
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/girando.jpg")));
                    if (primeiraVezTocando) {
                        primeiraVezTocando = false;
                        path = "sons/girando.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    } else {
                        musica.stop();
                        path = "sons/girando.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    }
                }
            }.start();
        } else if (e.getKeyCode() == KeyEvent.VK_Q) {
            new Thread() {

                public void run() {
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/foca.jpg")));
                    if (primeiraVezTocando) {
                        primeiraVezTocando = false;
                        path = "sons/foca.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    } else {
                        musica.stop();
                        path = "sons/foca.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    }
                }
            }.start();
        } else if (e.getKeyCode() == KeyEvent.VK_R) {
            new Thread() {

                public void run() {
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/leao.jpg")));
                    if (primeiraVezTocando) {
                        primeiraVezTocando = false;
                        path = "sons/leao.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    } else {
                        musica.stop();
                        path = "sons/leao.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    }
                }
            }.start();
        } else if (e.getKeyCode() == KeyEvent.VK_S) {
            new Thread() {

                public void run() {
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/corneta.png")));
                    if (primeiraVezTocando) {
                        primeiraVezTocando = false;
                        path = "sons/corneta.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    } else {
                        musica.stop();
                        path = "sons/corneta.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    }
                }
            }.start();
        } else if (e.getKeyCode() == KeyEvent.VK_T) {
            new Thread() {

                public void run() {
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cabra.jpg")));
                    if (primeiraVezTocando) {
                        primeiraVezTocando = false;
                        path = "sons/cabra.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    } else {
                        musica.stop();
                        path = "sons/cabra.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    }
                }
            }.start();
        } else if (e.getKeyCode() == KeyEvent.VK_U) {
            new Thread() {

                public void run() {
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vaca.jpg")));
                    if (primeiraVezTocando) {
                        primeiraVezTocando = false;
                        path = "sons/vaca.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    } else {
                        musica.stop();
                        path = "sons/vaca.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    }
                }
            }.start();
        } else if (e.getKeyCode() == KeyEvent.VK_V) {
            new Thread() {

                public void run() {
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bufalo.jpg")));
                    if (primeiraVezTocando) {
                        primeiraVezTocando = false;
                        path = "sons/bufalo.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    } else {
                        musica.stop();
                        path = "sons/bufalo.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    }
                }
            }.start();
        } else if (e.getKeyCode() == KeyEvent.VK_X) {
            new Thread() {

                public void run() {
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cavalo.jpg")));
                    if (primeiraVezTocando) {
                        primeiraVezTocando = false;
                        path = "sons/cavalo2.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    } else {
                        musica.stop();
                        path = "sons/cavalo2.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    }
                }
            }.start();
        } else if (e.getKeyCode() == KeyEvent.VK_W) {
            new Thread() {

                public void run() {
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/passaro.jpg")));
                    if (primeiraVezTocando) {
                        primeiraVezTocando = false;
                        path = "sons/passaro2.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    } else {
                        musica.stop();
                        path = "sons/passaro2.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    }
                }
            }.start();
        } else if (e.getKeyCode() == KeyEvent.VK_Y) {
            new Thread() {

                public void run() {
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/grito.jpg")));
                    if (primeiraVezTocando) {
                        primeiraVezTocando = false;
                        path = "sons/grito2.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    } else {
                        musica.stop();
                        path = "sons/grito2.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    }
                }
            }.start();
        } else if (e.getKeyCode() == KeyEvent.VK_Z) {
            new Thread() {

                public void run() {
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/aguia.jpg")));
                    if (primeiraVezTocando) {
                        primeiraVezTocando = false;
                        path = "sons/aguia.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    } else {
                        musica.stop();
                        path = "sons/aguia.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    }
                }
            }.start();
        } else {
            new Thread() {

                public void run() {
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/balada.jpg")));
                    if (primeiraVezTocando) {
                        primeiraVezTocando = false;
                        path = "sons/kuduro.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    } else {
                        musica.stop();
                        path = "sons/kuduro.mp3";
                        mp3File = new File(path);
                        musica = new MP3(mp3File);
                        musica.play();
                    }
                }
            }.start();
        }
    }

    public void keyReleased(KeyEvent e) {
    }

    public void keyTyped(KeyEvent e) {
    }
}
